<?php

/**
 * @file
 * Code for the OS2Web Kontaktblok feature.
 */
include_once 'os2web_kontaktblok.features.inc';

/**
 * Helper function to provide a kontaktblok node for views.
 *
 * return int nid of block node.
 */
function os2web_kontaktblok_get_block() {
  $result = 0;
  $menu = menu_get_active_trail();
  while ($item = array_pop($menu)) {
    $path = explode('/', $item['link_path']);
    if ($path[0] === 'taxonomy' && $path[1] === 'term') {
      $ent = taxonomy_term_load($path[2]);
      $field = field_get_items('taxonomy_term', $ent, 'field_node_reference_kontaktblok');
    }
    elseif ($path[0] === 'node') {
      $ent = node_load($path[1]);
      $field = field_get_items('node', $ent, 'field_node_reference_kontaktblok');
    }
    elseif ($path[1] == 0) {
      $node = menu_get_object();
      $field = field_get_items('node', $node,'field_node_reference_kontaktblok');
    }
    if (isset($field[0]['nid'])) {
      $result = $field[0]['nid'];
      break;
    }
  }
error_log($result);
  if ($result == 0) {
    // Try to find current nodes contact. These are for them who are not in menu.
    $node = menu_get_object();
    if ($node && $node->nid) {
      $field = field_get_items('node', $node, 'field_node_reference_kontaktblok');
      $result = $field[0]['nid'];
    }
  }
  return $result;
}
