<?php
define('ACADRE_CM_ACCESS_OPEN_CASE', '3');

/* Field information hooks */

function os2web_case_field_field_info() {
  return array(
      'case_ident' => array(
          'label' => t('ESDH Case'),
          'description' => 'Sags-id skal være på formen år/nummer eller år-nummer. Kun én værdi er tilladte.',
          'default_widget' => 'case_ident_widget',
          'default_formatter' => 'case_ident_formatter',
      ),
  );
}

function os2web_case_field_field_formatter_info() {
  return array(
      'case_ident_formatter' => array(
          'label' => t('ESDH Case includer'),
          'field types' => array('case_ident'),
      )
  );
}

function os2web_case_field_field_widget_info() {

  return array(
      'case_ident_widget' => array(
          'label' => t('Case Identifier'),
          'field types' => array('case_ident'),
      )
  );
}

/**
 * Field widget form hook
 *
 */
function os2web_case_field_field_widget_form(&$form, &$form_state, $field, $instance, $langcode, $items, $delta, $element) {
  $field_name = $field['field_name'];
  $field_type = $field['type'];
  $default = '';
  if (isset($form_state['node']->{$field_name}[$langcode][$delta][$field_type])) {
    $default = ($form_state['node']->{$field_name}[$langcode][$delta][$field_type])? : 0;
  }
  switch ($instance['widget']['type']) {
    case 'case_ident_widget':

      $element['case_ident'] = array(
          '#type' => 'textfield',
          '#title' => $element['#title'],
          '#description' => $element['#description'],
          '#default_value' => $default,
          '#required' => $element['#required'],
          '#weight' => isset($element['#weight']) ? $element['#weight'] : 0,
          '#delta' => $delta,
      );
      break;
  }
  return $element;
}

function os2web_case_field_field_is_empty($item, $field) {
  if (empty($item['case_ident'])) {
    return true;
  }
}

function os2web_case_field_field_validate($entity_type, $entity, $field, $instance, $langcode, $items, &$errors) {
  foreach ($items as $delta => $item) {
    $cases = explode(',',$item['case_ident']);
    foreach ($cases as $value) {
      $value = trim($value);     
      $valid = preg_match('/^\d{2}[-,\/]\d{1,20}$/', $value); // Adopt this for further testing
      if (!$valid && ($value!='')) {
        $errors[$field['field_name']][$langcode][$delta][] = array(
            'error' => 'Ugyldig fremstilling af sags-id. Sags-id skal være på formen år/nummer eller år-nummer. Flere sager skal være adskilt af , (komma).',
            'message' => t('%name: illegal value.', array('%name' => $instance['label'])),
            );
      }
    }
  }
}

/**
 * Field formatter hook
 *
 */
function os2web_case_field_field_formatter_view($entity_type, $entity, $field, $instance, $langcode, $items, $display) {
  $element = array();
  switch ($display['type']) {
    case 'case_ident_formatter':
      foreach ($items as $delta => $item) {
        if ($item['case_ident']) {
          $cases = array();
          $ids = explode(',', $item['case_ident']);
          //error_log("Var: \$ids = " . print_r($ids, 1));
          foreach ($ids as $id) {
            if (!is_numeric($id)) {
              $pws = _os2web_pws_get_instance();
              $cases[] = $pws->lookupCase(trim($id));
            } else {
              $cases[] = trim($id);
            }
          }
          $element[$delta]['#markup'] = '<div class="fullcaserender">' . theme('esdh_case', array('id' => $cases)) . '</div>';
        }
      }
      break;
  }
  return $element;
}

function os2web_case_field_theme() {
  return array(
      'esdh_case' => array(
          'variables' => array('id' => FALSE),
      ),
  );
}

function theme_esdh_case($vars) {
  $ids = $vars['id'];
  drupal_load('module', 'os2web_pws');
  $pws = _os2web_pws_get_instance();
  if (!is_array($ids)) {
    $ids = array($ids);
  }
  $docids = array();
  foreach ($ids as $id) {
    $case = $pws->fetchCase($id);
//    error_log("Var: \$case = " . print_r($case, 1));
    if (FALSE === $case) {
      continue; // Ignore failed case lookups
    }
    $valid = _os2web_case_field_case_access($id);
    if (!$valid) {
      //  $html .= '<p id="casenotpublic">This case is not publicly available.</p>';
      //  return $html;
      continue; // Ignore hidden cases
    }
    $docs = $pws->getCaseDocs($id);
    foreach ($docs as $doc) {
      $docids[] = (int) $doc->Document->DocumentIdentifier;
    }
  }
  $html = theme('esdh_document', array('id' => $docids, 'iscase' => true));
  return $html;
}

function _os2web_case_field_case_access($caseid) {
  drupal_load('module', 'os2web_pws');
  $pws = _os2web_pws_get_instance();
  $case = $pws->fetchCase($caseid);
  if (FALSE === $case) {
    return FALSE;
  }
  $access_grant = array(
      'accesscode' => 'KK',
      'restricted' => ACADRE_CM_ACCESS_OPEN_CASE,
  );
  $access = array(
      'accesscode' => $case->AccessCode,
      'restricted' => $case->RestrictedFromPublicText,
  );
  return _os2web_case_field_array_compare($access, $access_grant);
}

function _os2web_case_field_array_compare(array $a1, array $a2) {
  $result = true;
  foreach ($a1 as $key => $value) {
    if (isset($a2[$key]) && $a2[$key] === $value) {
      $result = $result && true;
    } else {
      $result = $result && false;
    }
  }
  return $result;
}
